<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address_checkbox</name>
   <tag></tag>
   <elementGuidId>d3260fdd-42fb-404f-9b88-da4492879c21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flexCheckDefault</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flexCheckDefault']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Address For Further Communication&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6283030-7a08-4b77-b2cb-9ef010cff567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>c0251487-2d7b-4214-b7cf-44e90f7667a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>29ed5feb-7ef2-49b0-8e9b-6eb913f6f3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexCheckDefault</value>
      <webElementGuid>78584ba6-8780-4462-8046-5c205d5492a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flexCheckDefault&quot;)</value>
      <webElementGuid>a0d0956d-f4dc-4d33-aefc-5444cefda282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flexCheckDefault']</value>
      <webElementGuid>163c5051-6664-4144-b684-e1989837693e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cardforADet']/div[2]/div[7]/div/div/input</value>
      <webElementGuid>dd5e1daa-ad58-4ba6-98e1-d73ad71ad164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>f6885afc-4db6-4515-8da7-bb7bdded9d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'flexCheckDefault']</value>
      <webElementGuid>e2955fe2-0a85-41ad-ad6c-dffe319425de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
