<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bank_Detaiis_status</name>
   <tag></tag>
   <elementGuidId>fa0182f7-cf43-4dd0-9242-0f9e47a50443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clmanstxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='clmanstxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Claimant Pass book Copy Received*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f0e7b50c-6643-4d5b-91a2-7c561f4e0ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>007e93ed-76eb-4300-bd3b-0fb1a6491404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clmanstxt</value>
      <webElementGuid>e7be86bc-10d4-474f-a2aa-5a524584c985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'2','errlblclmanstxt','clmanstxtdiv')</value>
      <webElementGuid>4bc6c5f2-111c-4c13-9caa-f6da9adc07f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                Select
                                                                Yes
                                                                No
                                                            </value>
      <webElementGuid>19ceaaf6-72ea-4901-96ce-9f492bfcd488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clmanstxt&quot;)</value>
      <webElementGuid>334d40be-82b3-4b36-b60a-025ac688afec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='clmanstxt']</value>
      <webElementGuid>6b0a0353-e656-4701-a7c3-78fe41fb2be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='clmanstxtdiv']/div/select</value>
      <webElementGuid>20606af4-5cc5-41fd-b925-0023482603c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reported On'])[1]/following::select[1]</value>
      <webElementGuid>a648d996-931f-4c96-82ec-0dadb7fb3e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reported By'])[1]/following::select[1]</value>
      <webElementGuid>6c7ea3aa-d95c-4862-a1e9-19c2348edb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claimant Pass book Copy Received*'])[1]/preceding::select[1]</value>
      <webElementGuid>872fd746-1893-4ee3-b6da-4e6bfc571e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Death Benefit'])[2]/preceding::select[2]</value>
      <webElementGuid>a3e690f9-71b1-46d5-9e63-adbd0dc96d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/select</value>
      <webElementGuid>247981ee-3f72-4465-a7b1-b1f4cf686a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'clmanstxt' and (text() = '
                                                                Select
                                                                Yes
                                                                No
                                                            ' or . = '
                                                                Select
                                                                Yes
                                                                No
                                                            ')]</value>
      <webElementGuid>8c3c625d-fbe4-4980-afe9-254d88adfcfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
