<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Benefit Type</name>
   <tag></tag>
   <elementGuidId>10c06222-8b86-4d21-98e3-c6ba4827b4b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deathnfttxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='deathnfttxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#deathnfttxt</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3a1b33a0-e895-4d12-900c-39ef6d96dff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>5aad4258-2407-437b-b6f6-c8220a2bcc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deathnfttxt</value>
      <webElementGuid>a81db49a-1394-4ef2-8434-de7c13781142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'2','errlbldeathnfttxt','deathnfttxtdiv')</value>
      <webElementGuid>8b16267f-b183-4f20-9b5d-3c51e1280203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                Select
                                                                LUMPSUM
                                                                INSTALLMENT
                                                            </value>
      <webElementGuid>a4981907-6de7-4b7c-9e6e-3dc86425afa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deathnfttxt&quot;)</value>
      <webElementGuid>e13489ae-33ff-47ee-b040-378010d1538f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='deathnfttxt']</value>
      <webElementGuid>1740f2d5-018a-4f08-b0a5-36ee7db35c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deathnfttxtdiv']/div/select</value>
      <webElementGuid>94f499a4-749b-4917-82dc-32fced56f063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claimant Pass book Copy Received*'])[1]/following::select[1]</value>
      <webElementGuid>c3288f9b-4f20-4b77-99bf-48d4ab786f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reported On'])[1]/following::select[2]</value>
      <webElementGuid>f3568a08-ccd9-40dc-b8e1-60acecbdbff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Death Benefit'])[2]/preceding::select[1]</value>
      <webElementGuid>034df876-06c3-440c-b034-13430a603ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/preceding::select[1]</value>
      <webElementGuid>7ab0f19e-4e72-4cc8-92f8-e41fd8c5479f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/select</value>
      <webElementGuid>446b7b25-3522-4bf3-be3f-2e411abf39ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'deathnfttxt' and (text() = '
                                                                Select
                                                                LUMPSUM
                                                                INSTALLMENT
                                                            ' or . = '
                                                                Select
                                                                LUMPSUM
                                                                INSTALLMENT
                                                            ')]</value>
      <webElementGuid>be4c225d-68c9-46ab-bbb4-b325a8f8c12e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
