<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cause_of_Death</name>
   <tag></tag>
   <elementGuidId>373aadb0-5c6c-4f36-9b47-5e725503262a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CODdeath</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CODdeath']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cause Of Death&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>114aeaca-c11f-449d-afd0-62c988798ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>b44de634-ff5e-4855-a18e-66d6de0dcf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CODdeath</value>
      <webElementGuid>f012611a-fc05-450d-ba4f-0381120cc163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'2','errlblCODdeath','CODdeathdiv')</value>
      <webElementGuid>81b73a36-a5b7-4e31-a5a0-4c6ea02b2175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectIll Health - Alcohol or Drug use DisordersIll Health - Alzheimers DiseaseIll Health - AsthmaIll Health - Benign Prostatic HyperplasiaIll Health - CancerIll Health - Cardio Vascular DiseasesIll Health - Child hood DiseasesIll Health - Chronic Obstructive Pulmonary Disease COPDIll Health - Cirrhosis of LiverIll Health - Congenital abnormalitiesIll Health - Diabetes Mellitus DMIll Health - Diarrhea or Cholera DiseaseIll Health - Digestive DiseaseIll Health - Genetic DiseasesIll Health - Endocrine or Nutritional DisordersIll Health - EpilepsyIll Health - Hepatitis BIll Health - Hepatitis CIll Health - HIV or AIDSIll Health - HyperTension or BPIll Health - Infectious and Parasitic DiseasesIll Health - Inflammatory Heart DiseasesIll Health - Iron Deficiency or AnemiaIll Health - Ischemic Heart Disease IHDIll Health - LeukemiaIll Health - Lymphomas or Multiple MyelomaIll Health - Malaria or Typhoid or Dengue or FluIll Health - Maternal ConditionsIll Health - MeningitisIll Health - Musculoskeletal DiseasesIll Health - NeoplasmsIll Health - Nephritis or NephropathyIll Health - Neuro Psychiatric DisordersIll Health - Parkinsons DiseaseIll Health - UlcersIll Health - Perinatal ConditionsIll Health - Respiratory InfectionsIll Health - Rheumatic Heart DiseaseIll Health - SKIN DiseasesIll Health - Sexual DiseasesIll Health - TetanusIll Health - Tropical DiseaseIll Health - TuberCulosis TBIll Health - Kidney FailureIll Health - Heart AttackIll Health - ParalysisIll Health - Multi Organ FailuresIll Health - Sun StrokeIll Health - ComaIll Health - Fever         Malaria Dengue Chickungunya Plague Cholera ViralIll Health - RabiesIll Health - Heart Attack or Cardio Respiratory Arrest or Myocardial InfarctionIll Health - PyrexiaIll Health - hypoxiaIll Health - Brain HemorrhageIll Health - Sepsis or SepticemiaIll Health - Brain TumorIll Health - Diseases related to PancreasIll Health - Hepatic EncephalopathyIll Health - ArthritisIll Health - SLE Systemic Lupus Erythematosus  AutoImmune DiseaseIll Health - Gangrene of small intestineIll Health - IIl health –Covid 19Accident - Injury DeathAccident - Natural Calamities or EnvironmentalAccident - AssaultAccident - Fell down or Slip downAccident - FirearmAccident - DrowningAccident - BurningAccident - Road Traffic AccidentAccident - VoilenceAccident - Suffocation or AsyphexiaAccident - PoisoningAccident - PedestrianAccident - MurderAccident - Inhaling PesticideAccident - UnIntentionalAccident - Accident of Pillion RiderAccident - Thunder StormAccident - Animal AttackAccident - Electrical ShockAccident - Death due to Adventurous HobbiesAccident - ViolenceSuicide - SuicideSuicide - WARSuicide - Intentional Injurier</value>
      <webElementGuid>143282fd-ecd2-4e02-9769-66eacd684b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CODdeath&quot;)</value>
      <webElementGuid>1ea727b1-d81e-4463-9991-4dbedb39f9fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CODdeath']</value>
      <webElementGuid>c5de97dc-acc7-4541-ae35-70f794f1be9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CODdeathdiv']/div/select</value>
      <webElementGuid>56b69740-1e5b-4217-b4ea-98178b34ee2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Of Death'])[1]/following::select[1]</value>
      <webElementGuid>401ec54c-5c30-458a-bc63-1f1de0bcf31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Date'])[1]/following::select[1]</value>
      <webElementGuid>a0c0ca4d-fe23-414a-af61-edfbd6d6469b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cause Of Death'])[1]/preceding::select[1]</value>
      <webElementGuid>5c392d60-2491-48d8-8a1b-2c36d8b1ee34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Place Of Death'])[1]/preceding::select[1]</value>
      <webElementGuid>508904d9-83b5-427a-b55b-4606e16d2344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>a97582d1-e3f0-4153-81b1-724f81f18e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id='CODdeath']/option[text()=&quot;Ill Health - Cancer&quot;]</value>
      <webElementGuid>79bd1e05-a80b-40dd-b94b-6945398904da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
