<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Death_Date</name>
   <tag></tag>
   <elementGuidId>ba4ca01d-8aae-4b83-b5e7-653f220733f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DODdt_dthClms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DODdt_dthClms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DODdt_dthClms</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adfdb0f6-c803-40e9-a73f-9adc6d5e490e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c3095ed-0446-4da2-a6e8-de2766206bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DODdt_dthClms</value>
      <webElementGuid>98f5293d-fa97-48f1-b223-5527b13b961a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>bc4f10fd-6af5-4074-bca4-be338aa22b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>931e1437-ea1e-4e0a-a5ff-50b7a01130d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'1','errlblDODdt_dthClms','doddiv_dthClms')</value>
      <webElementGuid>8a278b51-d192-4444-9f49-9452ab5772c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'1','errlblDODdt_dthClms','doddiv_dthClms')</value>
      <webElementGuid>1ce7750d-24f2-4fe7-a05b-43dbe5167681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>DateFormat(event)</value>
      <webElementGuid>2a8aeebb-1e0e-474e-b3e6-631ce7caeab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MM-YYYY</value>
      <webElementGuid>65a7e559-f51a-4c1d-9d0f-c25ed105c00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>81b4bf5a-002c-4490-8b69-79be28ea30a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DODdt_dthClms&quot;)</value>
      <webElementGuid>1bc6cb1d-da7e-4a29-8eda-1bb50000e4f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DODdt_dthClms']</value>
      <webElementGuid>3a500073-52cd-42b4-9fed-c39548427849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DODdtdiv_dthClms']/div/input</value>
      <webElementGuid>b942ed91-bcb9-4a70-a0a1-e875e1ed6a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>a104d9fd-7341-4d51-aadf-6e7374771643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DODdt_dthClms' and @placeholder = 'DD-MM-YYYY']</value>
      <webElementGuid>ac596054-68b2-4c1a-8932-3f1d677fa115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
