<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Phone_no</name>
   <tag></tag>
   <elementGuidId>23d3f6d4-0676-4c4e-a9ce-f719fdb75b74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phntxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phntxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#phntxt</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6810af6a-6237-4907-9f7a-f8b7d59b96ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee644bb4-2877-48e6-ba5b-8e09f6a49714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phntxt</value>
      <webElementGuid>ccc0b46f-edea-4ca1-8bb8-7fa8f6e29bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>43d3e7fa-7d02-41cb-b284-8a90b9346665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>97b2fe00-65b9-43f4-be0c-0ccdbf98668a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'3','errlblphntxt','phntxtdiv')</value>
      <webElementGuid>eab7350b-caf3-4cf8-9f90-3ed9fa4d83cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>NumberOnly(event)</value>
      <webElementGuid>1c182fe5-a005-41c0-a7c0-0e63874930ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c9fa336a-1c4f-41a9-b945-c414c9c1a80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phntxt&quot;)</value>
      <webElementGuid>b0f10399-d5aa-41fb-8d81-f78dfd887b78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phntxt']</value>
      <webElementGuid>ac7ed28e-58a5-4e48-81e3-68ed77ac1f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='phntxtdiv']/div/input</value>
      <webElementGuid>ce0ac444-f490-46f4-a1b0-92a7a673e7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>b83ca1b0-f649-416c-ae94-9d1d88bb8846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'phntxt']</value>
      <webElementGuid>8a45162f-57cc-4660-a042-aca69d699998</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
