<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reported By</name>
   <tag></tag>
   <elementGuidId>036c701f-23b9-4b81-b3f8-e1b5852ac016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rptbytxt_dthClms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rptbytxt_dthClms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rptbytxt_dthClms</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f781636-c92f-4a62-a981-ecd419c400fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87bab01d-5213-4bfe-8d75-534d673ad402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rptbytxt_dthClms</value>
      <webElementGuid>852410eb-13e6-4a8a-bd80-03b324777753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>93d367d9-4d3a-4ce6-b055-aed38a5a8167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>2803901d-9a1e-4419-a8ab-80cb3f9d2ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'1','errlblrptbytxt_dthClms','rptbytxtdiv_dthClms')</value>
      <webElementGuid>c752cfb4-3f48-49c6-bc9d-69f3b02a14cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>AllowsAlphabeticOnly(event)</value>
      <webElementGuid>93cce0b7-07a0-4b92-909b-421d5f6629d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a01a6827-5808-4562-9c7f-172db8806335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rptbytxt_dthClms&quot;)</value>
      <webElementGuid>449b557c-34f1-4541-a1f5-040a4865c3c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rptbytxt_dthClms']</value>
      <webElementGuid>04abc4c6-c24f-41e1-893a-6ccc18904320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rptbytxtdiv_dthClms']/div/input</value>
      <webElementGuid>2ef9faa4-0a50-4c34-867a-11f2e6bac567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>fa81f0b2-bd1d-4a2a-9c24-6a6c7c40a496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'rptbytxt_dthClms']</value>
      <webElementGuid>e552f979-4093-4d80-992f-f59552666beb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
