<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reported_Date</name>
   <tag></tag>
   <elementGuidId>86541c00-143f-4430-80b8-9cc089b97c54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rptdt_dthClms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rptdt_dthClms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rptdt_dthClms</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab542e5b-dfd5-44df-ab17-26428088b6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ba8b1f2-73ce-46d1-b241-06a56d6d6591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rptdt_dthClms</value>
      <webElementGuid>2554c52e-fbb1-4bd5-b815-ea10c5a67ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>48c66efa-4345-40b6-b2b5-8231b418d00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>5ba1758b-fdb4-4e26-bce3-4015a6ae501c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'1','errlblrptdt_dthClms','rptdtdiv_dthClms')</value>
      <webElementGuid>3a4e5dfd-1221-42fb-9ef6-33a5785a4ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'1','errlblrptdt_dthClms','rptdtdiv_dthClms')</value>
      <webElementGuid>6822779e-feee-4253-bb05-e7e7c1c1789f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>DateFormat(event)</value>
      <webElementGuid>cd64dacb-fcc0-4d1a-9976-bc6532558d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MM-YYYY</value>
      <webElementGuid>fc67a2ed-025c-4754-a767-bf39eb9a9fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>91abb506-f5ac-449f-add3-5ff7dfe2ca71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rptdt_dthClms&quot;)</value>
      <webElementGuid>abec162a-0291-40ed-bf55-3cb3d70b7e66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rptdt_dthClms']</value>
      <webElementGuid>6835f146-d9a0-4686-8ce1-1b9ff7579eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rptdtdiv_dthClms']/div/input</value>
      <webElementGuid>e283e115-d9f8-4f6c-8e7b-e2d85bd7a0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>930fdddc-3840-41ca-8300-7ecd7603274a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'rptdt_dthClms' and @placeholder = 'DD-MM-YYYY']</value>
      <webElementGuid>255a6d9c-46cb-40af-b62b-18e27debf993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
