<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Request_Date</name>
   <tag></tag>
   <elementGuidId>e122ff24-0ee5-43d7-9725-b657ca23506d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtreqdt_dthClms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtreqdt_dthClms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtreqdt_dthClms</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd819bcd-67d2-43e1-af65-10895a6122ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85cf3fba-03f9-4af3-8a4e-4005c73c75bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtreqdt_dthClms</value>
      <webElementGuid>ea985440-9835-4e88-9fcc-5c2306ec84bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>e68c83ff-ac56-483b-ba7b-2561310ba77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>fe5a6e5e-a6a6-4236-a88d-2bfc96386c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'1','errlbltxtreqdt_dthClms','reqeustdiv_dthClms')</value>
      <webElementGuid>2f0b5ee5-1b64-4096-b54d-d6ebc2f575c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'1','errlbltxtreqdt_dthClms','reqeustdiv_dthClms')</value>
      <webElementGuid>e856cb61-ee64-4462-bed4-7053f939caa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>DateFormat(event)</value>
      <webElementGuid>57a17132-04f3-4bbd-b5fd-dffe11bb359c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MM-YYYY</value>
      <webElementGuid>c004fabf-a1a6-4d23-9fa0-4be78034f8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>66457b54-2ba8-4004-a26c-91275c6b6e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtreqdt_dthClms&quot;)</value>
      <webElementGuid>8f9d8a13-a5ab-4d55-93f2-f87b19c82f7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtreqdt_dthClms']</value>
      <webElementGuid>465689fa-55b3-4d9d-838b-1355c591dae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reqeustdiv_dthClms']/div/input</value>
      <webElementGuid>6709bca1-6d6b-49a8-afd1-bd37c837809d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>aa440a6d-4b5a-4f7f-a30f-a1115092c426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtreqdt_dthClms' and @placeholder = 'DD-MM-YYYY']</value>
      <webElementGuid>f7999092-e3f1-4782-8d7d-6539771025b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
