<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Whatsapp_no</name>
   <tag></tag>
   <elementGuidId>b1f6bc23-f7d6-42ce-80e9-957507f31262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#whatsappmobtxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='whatsappmobtxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#whatsappmobtxt</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27f62c2e-e8fc-4ff0-b4f0-7893ca949c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3973d5af-c4e4-43da-8236-1d98da1f7a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>whatsappmobtxt</value>
      <webElementGuid>c62dd72b-3c54-4dfb-a785-37688dfe6ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eacde2e8-689d-423c-b5f4-1c4e332c6183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>80af0cf1-356e-4e02-a4d6-075068560f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'3','errlblwhatsappmobtxt','whatsappmobtxtdiv')</value>
      <webElementGuid>34a566af-592c-446e-be1f-7ff54ad65018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>NumberOnly(event)</value>
      <webElementGuid>1ffc71c3-4cee-488f-ad62-7d01e12a5dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e4786cc4-fdba-4b0d-87cd-8330c350d350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;whatsappmobtxt&quot;)</value>
      <webElementGuid>8e9b6c1f-20dc-44e1-afaa-f0e9722579b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='whatsappmobtxt']</value>
      <webElementGuid>1f911847-37c7-45de-8bb9-e910e7e65b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whatsappmobtxtdiv']/div/input</value>
      <webElementGuid>69ae0881-67e5-4ea8-b981-0d4e1c05a241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/input</value>
      <webElementGuid>5b0b222b-3f12-4dff-a186-850c4d0a107c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'whatsappmobtxt']</value>
      <webElementGuid>5556d41f-7ae0-4f2b-8ff3-509ae2d8b73b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
