<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assessor Remark</name>
   <tag></tag>
   <elementGuidId>c6f88b91-bd9e-4688-86e7-e7861e563a3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtArDTremarks_A</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtArDTremarks_A']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtArDTremarks_A</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dfd336d5-7287-4480-a17f-47c5e14710a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control borderredcls</value>
      <webElementGuid>6f4fea4a-2378-4598-b09a-0406638969ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtArDTremarks_A</value>
      <webElementGuid>3ad8841c-43f7-435f-8def-ab5fda93cba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtArDTremarks_A</value>
      <webElementGuid>34ea5d48-338f-4cbc-afb4-11ec1bea0e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>be78ad18-c542-4e20-91df-0ad6535ad01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1500</value>
      <webElementGuid>a84fc782-d489-4847-afc6-6b053fb69d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>11ecabdc-ce94-4a86-bcba-31e80f08fd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>txtArDTremarks_A-error</value>
      <webElementGuid>14aa57a5-0700-4e66-8bde-c5c4d309c0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1d76321-a267-48b9-b959-d513b6d95605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtArDTremarks_A&quot;)</value>
      <webElementGuid>a9008595-0bf2-4e76-b4d7-4fb25126f9ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtArDTremarks_A']</value>
      <webElementGuid>a17aa219-e7ea-4a6d-8fc5-db9ad23e3f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmDT']/div/div[2]/textarea</value>
      <webElementGuid>c95c8a7e-2a76-4459-bd9e-70b740c6b123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0c87e8a0-870a-4ef5-96ce-46e47c3a0cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtArDTremarks_A' and @name = 'txtArDTremarks_A']</value>
      <webElementGuid>fad99a7e-84d3-4011-b0d7-9709b63632ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
