<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manager Select</name>
   <tag></tag>
   <elementGuidId>c397a77f-24ce-4aeb-a4fa-fd3f3029a753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ddlmanager</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddlmanager']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ddlmanager</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9f0f7f46-e0d1-439d-b62f-7f3563e3a3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-control</value>
      <webElementGuid>03c660b0-e962-4e8d-9a54-293bd8ec2460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddlmanager</value>
      <webElementGuid>5acbb98e-fbf0-4d3a-814e-70920768ae26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlmanager</value>
      <webElementGuid>b55af386-c50f-4390-8a28-5c3ffeff8565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NoneManager I ARJUN KOPPULA (R0163)Manager I Naresh Ameti (R0163)Manager I Sai Vijay Kumar K (R0160)Manager I MAMIDI MAHESHWAR REDDY (R0163)Manager I Mulinti Pradeep Reddy (R0163)Manager I Anand Raj (R0160)Manager II Lingerkar Naveen Kumar (R0162)Manager III NAVEEN L (R0149)Manager I Narasimhan I (R0160)Manager I Pyla Sai Madhavi Krishna (R0163)Manager III Pyla Sai Madhavi Krishna (R0149)Manager III P Manikandan (R0149)Manager III Punugoti Prasad (R0149)Manager III RAMESH PYDI (R0149)Manager I SIDAM SRIDEVI (R0163)Manager I Tamanna Sachdeva (R0160)</value>
      <webElementGuid>f731fcb7-13ee-4cfe-87f1-70b2d01deed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlmanager&quot;)</value>
      <webElementGuid>99eebc16-a560-4ab1-b520-164bfc2f1a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlmanager']</value>
      <webElementGuid>e5ae9a04-8a32-44e0-bded-27033cc4d059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmManager']/div/div/div/div/select</value>
      <webElementGuid>f4512fbc-95a2-4f8a-9bb5-bc8c6f87dcf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager'])[1]/following::select[1]</value>
      <webElementGuid>b3341e6b-82ea-44d1-8218-f9735b27801b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parallel Investigation'])[1]/following::select[1]</value>
      <webElementGuid>121ced50-2712-4eba-842f-b34e30062c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/preceding::select[1]</value>
      <webElementGuid>3d581c33-cf95-400c-80ea-12ad2d828466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[10]/preceding::select[1]</value>
      <webElementGuid>483f6594-b277-4ece-ba1b-9dbd81d0327b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div/div/select</value>
      <webElementGuid>71c5a91d-3e4e-4701-9581-d59c623f4c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ddlmanager' and @id = 'ddlmanager' and (text() = 'NoneManager I ARJUN KOPPULA (R0163)Manager I Naresh Ameti (R0163)Manager I Sai Vijay Kumar K (R0160)Manager I MAMIDI MAHESHWAR REDDY (R0163)Manager I Mulinti Pradeep Reddy (R0163)Manager I Anand Raj (R0160)Manager II Lingerkar Naveen Kumar (R0162)Manager III NAVEEN L (R0149)Manager I Narasimhan I (R0160)Manager I Pyla Sai Madhavi Krishna (R0163)Manager III Pyla Sai Madhavi Krishna (R0149)Manager III P Manikandan (R0149)Manager III Punugoti Prasad (R0149)Manager III RAMESH PYDI (R0149)Manager I SIDAM SRIDEVI (R0163)Manager I Tamanna Sachdeva (R0160)' or . = 'NoneManager I ARJUN KOPPULA (R0163)Manager I Naresh Ameti (R0163)Manager I Sai Vijay Kumar K (R0160)Manager I MAMIDI MAHESHWAR REDDY (R0163)Manager I Mulinti Pradeep Reddy (R0163)Manager I Anand Raj (R0160)Manager II Lingerkar Naveen Kumar (R0162)Manager III NAVEEN L (R0149)Manager I Narasimhan I (R0160)Manager I Pyla Sai Madhavi Krishna (R0163)Manager III Pyla Sai Madhavi Krishna (R0149)Manager III P Manikandan (R0149)Manager III Punugoti Prasad (R0149)Manager III RAMESH PYDI (R0149)Manager I SIDAM SRIDEVI (R0163)Manager I Tamanna Sachdeva (R0160)')]</value>
      <webElementGuid>1b31172e-1775-466b-8163-b51c86edfd26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
