<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Remark</name>
   <tag></tag>
   <elementGuidId>f6dfa193-96a8-4185-afb7-34a33bb21025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtremarksM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtremarksM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtremarksM</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3e8a3945-8bdc-43c6-a235-a1b97a6843cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control borderredcls</value>
      <webElementGuid>3ac0d4b4-665a-46eb-85cf-ceb6bd98d50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtremarksM</value>
      <webElementGuid>9ec8828f-1201-40fe-bc1e-7858d5560a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtremarksM</value>
      <webElementGuid>dbbda7ec-9021-44d1-bef1-7bec6fd6e142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>0780252e-3195-4673-b2ec-e8c651cca47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1500</value>
      <webElementGuid>de9ca3c0-b389-4a6a-a660-d4fb9703cf02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>86e953e4-7278-4e0c-a1ec-0419f143b244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>txtremarksM-error</value>
      <webElementGuid>8e013cf8-ad09-48d8-ad8a-131045b77699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e6773ab-0b6f-4b5d-9977-c08e393c70e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtremarksM&quot;)</value>
      <webElementGuid>168b3c01-1bf3-48e4-8bfd-7e86cb504be7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtremarksM']</value>
      <webElementGuid>a64f93a2-fa31-4dda-836a-f53a44ed9562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmManager']/div/div/div/div[2]/textarea</value>
      <webElementGuid>0a776936-bbc0-4bad-a00c-47c733404db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div/div[2]/textarea</value>
      <webElementGuid>fadb686f-d546-4b79-a556-908404f43d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtremarksM' and @name = 'txtremarksM']</value>
      <webElementGuid>9f904d3f-5eab-4b89-b301-b5972f4baa67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
