<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cause Of Death</name>
   <tag></tag>
   <elementGuidId>4de90f4f-7405-4f8b-ae0a-ccaa32d3f31d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CODdeath</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CODdeath']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cause Of Death&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3c652736-6a29-4a45-b9bb-522d9db2b9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>c4e2231b-e84e-4fc3-9bde-31f49f33861a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CODdeath</value>
      <webElementGuid>070237af-da80-4027-a4d3-76c4b0b1d5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'2','errlblCODdeath','CODdeathdiv')</value>
      <webElementGuid>0b134e40-4fe4-442e-a739-b765dfe019d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>f04adee0-14d5-44e5-a372-d79f9b73f70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectIll Health - Alcohol or Drug use DisordersIll Health - Alzheimers DiseaseIll Health - AsthmaIll Health - Benign Prostatic HyperplasiaIll Health - CancerIll Health - Cardio Vascular DiseasesIll Health - Child hood DiseasesIll Health - Chronic Obstructive Pulmonary Disease COPDIll Health - Cirrhosis of LiverIll Health - Congenital abnormalitiesIll Health - Diabetes Mellitus DMIll Health - Diarrhea or Cholera DiseaseIll Health - Digestive DiseaseIll Health - Genetic DiseasesIll Health - Endocrine or Nutritional DisordersIll Health - EpilepsyIll Health - Hepatitis BIll Health - Hepatitis CIll Health - HIV or AIDSIll Health - HyperTension or BPIll Health - Infectious and Parasitic DiseasesIll Health - Inflammatory Heart DiseasesIll Health - Iron Deficiency or AnemiaIll Health - Ischemic Heart Disease IHDIll Health - LeukemiaIll Health - Lymphomas or Multiple MyelomaIll Health - Malaria or Typhoid or Dengue or FluIll Health - Maternal ConditionsIll Health - MeningitisIll Health - Musculoskeletal DiseasesIll Health - NeoplasmsIll Health - Nephritis or NephropathyIll Health - Neuro Psychiatric DisordersIll Health - Parkinsons DiseaseIll Health - UlcersIll Health - Perinatal ConditionsIll Health - Respiratory InfectionsIll Health - Rheumatic Heart DiseaseIll Health - SKIN DiseasesIll Health - Sexual DiseasesIll Health - TetanusIll Health - Tropical DiseaseIll Health - TuberCulosis TBIll Health - Kidney FailureIll Health - Heart AttackIll Health - ParalysisIll Health - Multi Organ FailuresIll Health - Sun StrokeIll Health - ComaIll Health - Fever         Malaria Dengue Chickungunya Plague Cholera ViralIll Health - RabiesIll Health - Heart Attack or Cardio Respiratory Arrest or Myocardial InfarctionIll Health - PyrexiaIll Health - hypoxiaIll Health - Brain HemorrhageIll Health - Sepsis or SepticemiaIll Health - Brain TumorIll Health - Diseases related to PancreasIll Health - Hepatic EncephalopathyIll Health - ArthritisIll Health - SLE Systemic Lupus Erythematosus  AutoImmune DiseaseIll Health - Gangrene of small intestineIll Health - IIl health –Covid 19Accident - Injury DeathAccident - Natural Calamities or EnvironmentalAccident - AssaultAccident - Fell down or Slip downAccident - FirearmAccident - DrowningAccident - BurningAccident - Road Traffic AccidentAccident - VoilenceAccident - Suffocation or AsyphexiaAccident - PoisoningAccident - PedestrianAccident - MurderAccident - Inhaling PesticideAccident - UnIntentionalAccident - Accident of Pillion RiderAccident - Thunder StormAccident - Animal AttackAccident - Electrical ShockAccident - Death due to Adventurous HobbiesAccident - ViolenceSuicide - SuicideSuicide - WARSuicide - Intentional Injurier</value>
      <webElementGuid>68ccf3f8-2437-461c-be1a-99c56e00f91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CODdeath&quot;)</value>
      <webElementGuid>6440280b-cd2b-4f08-90a3-d9c99f4b34aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CODdeath']</value>
      <webElementGuid>5f4d9849-d837-4e05-a960-aa89f42d8ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CODdeathdiv']/div/select</value>
      <webElementGuid>249c9cb6-46ea-4fc8-8c88-fbc8803ac79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Of Death'])[1]/following::select[1]</value>
      <webElementGuid>321ceda3-6f4f-4162-b9bf-c8cc56b7968f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Date'])[1]/following::select[1]</value>
      <webElementGuid>62e2576d-c521-4966-8f5a-cb8a9b7852a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cause Of Death'])[1]/preceding::select[1]</value>
      <webElementGuid>9c2c83b9-0c56-43b7-bedb-886f70e93dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Place Of Death'])[1]/preceding::select[1]</value>
      <webElementGuid>7b1527c8-b5db-4126-86e3-d9226c0d287d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>c60a9edc-7a2f-47a0-81ee-b4ca9a4b57c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CODdeath' and @selected = 'selected' and (text() = 'SelectIll Health - Alcohol or Drug use DisordersIll Health - Alzheimers DiseaseIll Health - AsthmaIll Health - Benign Prostatic HyperplasiaIll Health - CancerIll Health - Cardio Vascular DiseasesIll Health - Child hood DiseasesIll Health - Chronic Obstructive Pulmonary Disease COPDIll Health - Cirrhosis of LiverIll Health - Congenital abnormalitiesIll Health - Diabetes Mellitus DMIll Health - Diarrhea or Cholera DiseaseIll Health - Digestive DiseaseIll Health - Genetic DiseasesIll Health - Endocrine or Nutritional DisordersIll Health - EpilepsyIll Health - Hepatitis BIll Health - Hepatitis CIll Health - HIV or AIDSIll Health - HyperTension or BPIll Health - Infectious and Parasitic DiseasesIll Health - Inflammatory Heart DiseasesIll Health - Iron Deficiency or AnemiaIll Health - Ischemic Heart Disease IHDIll Health - LeukemiaIll Health - Lymphomas or Multiple MyelomaIll Health - Malaria or Typhoid or Dengue or FluIll Health - Maternal ConditionsIll Health - MeningitisIll Health - Musculoskeletal DiseasesIll Health - NeoplasmsIll Health - Nephritis or NephropathyIll Health - Neuro Psychiatric DisordersIll Health - Parkinsons DiseaseIll Health - UlcersIll Health - Perinatal ConditionsIll Health - Respiratory InfectionsIll Health - Rheumatic Heart DiseaseIll Health - SKIN DiseasesIll Health - Sexual DiseasesIll Health - TetanusIll Health - Tropical DiseaseIll Health - TuberCulosis TBIll Health - Kidney FailureIll Health - Heart AttackIll Health - ParalysisIll Health - Multi Organ FailuresIll Health - Sun StrokeIll Health - ComaIll Health - Fever         Malaria Dengue Chickungunya Plague Cholera ViralIll Health - RabiesIll Health - Heart Attack or Cardio Respiratory Arrest or Myocardial InfarctionIll Health - PyrexiaIll Health - hypoxiaIll Health - Brain HemorrhageIll Health - Sepsis or SepticemiaIll Health - Brain TumorIll Health - Diseases related to PancreasIll Health - Hepatic EncephalopathyIll Health - ArthritisIll Health - SLE Systemic Lupus Erythematosus  AutoImmune DiseaseIll Health - Gangrene of small intestineIll Health - IIl health –Covid 19Accident - Injury DeathAccident - Natural Calamities or EnvironmentalAccident - AssaultAccident - Fell down or Slip downAccident - FirearmAccident - DrowningAccident - BurningAccident - Road Traffic AccidentAccident - VoilenceAccident - Suffocation or AsyphexiaAccident - PoisoningAccident - PedestrianAccident - MurderAccident - Inhaling PesticideAccident - UnIntentionalAccident - Accident of Pillion RiderAccident - Thunder StormAccident - Animal AttackAccident - Electrical ShockAccident - Death due to Adventurous HobbiesAccident - ViolenceSuicide - SuicideSuicide - WARSuicide - Intentional Injurier' or . = 'SelectIll Health - Alcohol or Drug use DisordersIll Health - Alzheimers DiseaseIll Health - AsthmaIll Health - Benign Prostatic HyperplasiaIll Health - CancerIll Health - Cardio Vascular DiseasesIll Health - Child hood DiseasesIll Health - Chronic Obstructive Pulmonary Disease COPDIll Health - Cirrhosis of LiverIll Health - Congenital abnormalitiesIll Health - Diabetes Mellitus DMIll Health - Diarrhea or Cholera DiseaseIll Health - Digestive DiseaseIll Health - Genetic DiseasesIll Health - Endocrine or Nutritional DisordersIll Health - EpilepsyIll Health - Hepatitis BIll Health - Hepatitis CIll Health - HIV or AIDSIll Health - HyperTension or BPIll Health - Infectious and Parasitic DiseasesIll Health - Inflammatory Heart DiseasesIll Health - Iron Deficiency or AnemiaIll Health - Ischemic Heart Disease IHDIll Health - LeukemiaIll Health - Lymphomas or Multiple MyelomaIll Health - Malaria or Typhoid or Dengue or FluIll Health - Maternal ConditionsIll Health - MeningitisIll Health - Musculoskeletal DiseasesIll Health - NeoplasmsIll Health - Nephritis or NephropathyIll Health - Neuro Psychiatric DisordersIll Health - Parkinsons DiseaseIll Health - UlcersIll Health - Perinatal ConditionsIll Health - Respiratory InfectionsIll Health - Rheumatic Heart DiseaseIll Health - SKIN DiseasesIll Health - Sexual DiseasesIll Health - TetanusIll Health - Tropical DiseaseIll Health - TuberCulosis TBIll Health - Kidney FailureIll Health - Heart AttackIll Health - ParalysisIll Health - Multi Organ FailuresIll Health - Sun StrokeIll Health - ComaIll Health - Fever         Malaria Dengue Chickungunya Plague Cholera ViralIll Health - RabiesIll Health - Heart Attack or Cardio Respiratory Arrest or Myocardial InfarctionIll Health - PyrexiaIll Health - hypoxiaIll Health - Brain HemorrhageIll Health - Sepsis or SepticemiaIll Health - Brain TumorIll Health - Diseases related to PancreasIll Health - Hepatic EncephalopathyIll Health - ArthritisIll Health - SLE Systemic Lupus Erythematosus  AutoImmune DiseaseIll Health - Gangrene of small intestineIll Health - IIl health –Covid 19Accident - Injury DeathAccident - Natural Calamities or EnvironmentalAccident - AssaultAccident - Fell down or Slip downAccident - FirearmAccident - DrowningAccident - BurningAccident - Road Traffic AccidentAccident - VoilenceAccident - Suffocation or AsyphexiaAccident - PoisoningAccident - PedestrianAccident - MurderAccident - Inhaling PesticideAccident - UnIntentionalAccident - Accident of Pillion RiderAccident - Thunder StormAccident - Animal AttackAccident - Electrical ShockAccident - Death due to Adventurous HobbiesAccident - ViolenceSuicide - SuicideSuicide - WARSuicide - Intentional Injurier')]</value>
      <webElementGuid>54412f79-6b9d-4ce8-8d4b-e0efacf5b370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
