<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Policy _Details</name>
   <tag></tag>
   <elementGuidId>542c8a91-09d3-4331-823e-c27a53d15a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tabulator-cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grid-table']/div[2]/div/div/div[@tabulator-field=&quot;PolicyNo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;NN012101138858&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ba52cf4-f4d6-4d96-b11a-6f20f5ac600b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabulator-cell</value>
      <webElementGuid>c4152e40-523c-4652-ba06-abc084ef6b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>4844e416-4fc2-425f-b476-b2e354a6c69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabulator-field</name>
      <type>Main</type>
      <value>PolicyNo</value>
      <webElementGuid>60e73410-4cab-4afa-a40b-b9e5e41eb38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NN012101138858</value>
      <webElementGuid>d9cd00cd-c695-4407-9c83-4ee71d4a033d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-table&quot;)/div[@class=&quot;tabulator-tableholder&quot;]/div[@class=&quot;tabulator-table&quot;]/div[@class=&quot;tabulator-row tabulator-tree-level-0 tabulator-row-odd&quot;]/div[@class=&quot;tabulator-cell&quot;]</value>
      <webElementGuid>1f88b3f8-cb2b-444a-8daf-2c520cc16bb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid-table']/div[2]/div/div/div</value>
      <webElementGuid>9a9932fb-c3bc-499a-a4a6-3fe8517f9e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subref Agent Channel'])[1]/following::div[5]</value>
      <webElementGuid>33c7d2e1-6c30-437b-a864-3bc9b850d757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AgtLoc Channel'])[1]/following::div[9]</value>
      <webElementGuid>50b11fea-40eb-4bf7-a430-d380f2f2e05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAMESH M'])[1]/preceding::div[1]</value>
      <webElementGuid>816d8c12-e2ac-4b7c-a71a-b018372b45f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accident - Road Traffic Accident'])[1]/preceding::div[4]</value>
      <webElementGuid>2145129d-9657-494a-8077-d9b640611a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NN012101138858']/parent::*</value>
      <webElementGuid>45c23ee6-30a3-47ec-82aa-bc18d0eac62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>47e14c32-78ec-4085-ba02-cd9828813ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NN012101138858' or . = 'NN012101138858')]</value>
      <webElementGuid>de15455f-e7bb-437c-ace4-bfb02eb232ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
