<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Policy _Details</name>
   <tag></tag>
   <elementGuidId>542c8a91-09d3-4331-823e-c27a53d15a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tabulator-cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='grid-table']//div[@tabulator-field='PolicyNo' and contains(text(),'${policyNo}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;NN012101138858&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5ec6642-c80a-47f3-8361-c503549494b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabulator-cell</value>
      <webElementGuid>5887d977-458e-4e9f-9810-af383dde2eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>3bde02a9-8da7-407b-aa88-5fd10a304a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabulator-field</name>
      <type>Main</type>
      <value>PolicyNo</value>
      <webElementGuid>b3413bc6-c013-41c1-a9c7-d5cce677b2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NN012101138858</value>
      <webElementGuid>bc36ef63-6fbf-4e17-adb5-18b6fb9c28f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-table&quot;)/div[@class=&quot;tabulator-tableholder&quot;]/div[@class=&quot;tabulator-table&quot;]/div[@class=&quot;tabulator-row tabulator-tree-level-0 tabulator-row-odd&quot;]/div[@class=&quot;tabulator-cell&quot;]</value>
      <webElementGuid>88aee8df-592d-4507-b1ae-faa0af0a700a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid-table']/div[2]/div/div/div</value>
      <webElementGuid>b93ba67a-7a52-47e0-a120-f65133a0fa89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subref Agent Channel'])[1]/following::div[5]</value>
      <webElementGuid>208b2c38-c247-4490-803d-1b02d983c650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AgtLoc Channel'])[1]/following::div[9]</value>
      <webElementGuid>2e511ec6-e1d7-4278-a386-b1aeb9bbcc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAMESH M'])[1]/preceding::div[1]</value>
      <webElementGuid>7704d915-288b-4aa5-963c-8592cb140963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accident - Road Traffic Accident'])[1]/preceding::div[4]</value>
      <webElementGuid>0c433c0e-7a02-45d6-8f90-c3de412b6d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NN012101138858']/parent::*</value>
      <webElementGuid>dc7b2067-0929-47bd-ac02-8c4890ef5f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>8682dc2f-b4e5-4dd4-9eb4-f7f1d57e8711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NN012101138858' or . = 'NN012101138858')]</value>
      <webElementGuid>603a529b-8c2f-48b5-923d-45fd33bd398e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
