<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1remarks_text</name>
   <tag></tag>
   <elementGuidId>3fb38206-702d-436d-bc9a-c6d71dd8c80a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtArM1remarks</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtArM1remarks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;M1 Remarks&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f2923ec4-1593-41af-8485-b48ad641e44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>31636a90-6849-4bd0-b0d9-07db7b0f19ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtArM1remarks</value>
      <webElementGuid>32e85aa0-78f9-4a1b-a91e-994ae81f1d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtArM1remarks</value>
      <webElementGuid>b6ff7d93-0868-4341-9c07-292f0a7fb27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>FoucusOutFunction(this,'M1')</value>
      <webElementGuid>e3ef5bb1-f1d4-4d18-85f6-70ef120a2376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>93385018-2093-475f-8194-059675b0e722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1500</value>
      <webElementGuid>2b1fbe4e-93fa-4d85-9ec5-73195902c6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>09aec356-5f86-44de-a6cb-ebcdf1c86406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtArM1remarks&quot;)</value>
      <webElementGuid>8decfa6d-1453-4569-923c-ccbc1f02739a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtArM1remarks']</value>
      <webElementGuid>932c7d2d-05c8-4912-8579-cd57fb912130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divM1']/textarea</value>
      <webElementGuid>e872c65a-2f9d-45ae-915e-a948b72dff3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>6610317c-a66a-4bfa-bb15-79519f3ae21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtArM1remarks' and @name = 'txtArM1remarks']</value>
      <webElementGuid>5c6d3016-e39a-4e1c-9e8a-aa4a02276e0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
