<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_policy_no</name>
   <tag></tag>
   <elementGuidId>bd50c77a-b713-4de5-a5f3-076ed0034422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtbxfltrfldsval</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtbxfltrfldsval']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b6e29f5-c650-435c-b028-e14b4dc8ac53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txtbxfltrfldsvalcls</value>
      <webElementGuid>17f5d278-3f86-4e4a-afa3-4204fa8acb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11b4b505-c7d1-42fb-a9d4-4b3e083546b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtbxfltrfldsval</value>
      <webElementGuid>291f8a4b-abed-49c7-87bc-da7534c18698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>6aaf4157-beab-4b46-b3c6-a9600c9d10ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>updateFilter(this)</value>
      <webElementGuid>975b1df6-b452-488e-acc9-eb6d3e997083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6d7103f8-7e7e-48d3-8e0e-76e6087310c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtbxfltrfldsval&quot;)</value>
      <webElementGuid>a7b7988e-6224-4f2a-a42c-166709455859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtbxfltrfldsval']</value>
      <webElementGuid>7ecb462c-6e83-46bb-9035-88d3bc0a25bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hideshowbtndiv']/div/input</value>
      <webElementGuid>b17faac1-3162-461c-b4ad-b0a89f851515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/input</value>
      <webElementGuid>9fa39fa5-9a20-41bf-adb6-066b06989a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtbxfltrfldsval' and @placeholder = 'Search']</value>
      <webElementGuid>685454db-a52d-4051-b888-c52eb014e660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
