<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox</name>
   <tag></tag>
   <elementGuidId>f5e8c1ec-9ea6-445d-bfaf-3a40f5bd094c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.katalonDeHighlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;NNST2406061491 MANONMANI 10/06/2024 InForce Fully Paid Up CRM View View View View View View View 20/11/2024 07/03/2026 3 Days&quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52244bde-af35-4f4b-aef9-6f46913533ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>621bf530-fcc7-4c80-8084-7f66301a194b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> katalonDeHighlight</value>
      <webElementGuid>321487ac-9969-4a57-ad60-a77da189ee2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-table&quot;)/div[@class=&quot;tabulator-tableholder&quot;]/div[@class=&quot;tabulator-table&quot;]/div[@class=&quot;tabulator-row tabulator-selectable tabulator-row-odd tabulator-tree-level-0 tabulator-selected&quot;]/div[@class=&quot;tabulator-cell&quot;]/input[@class=&quot;katalonDeHighlight&quot;]</value>
      <webElementGuid>1d8363e4-2491-431d-b75c-09598dc1f7ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>f8d6e44a-b954-4e0e-a4e7-ecc772bef065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid-table']/div[2]/div/div/div/input</value>
      <webElementGuid>8e8c5225-4efd-4824-bf69-f7b62b9219aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>6e1a47f9-7854-4993-939e-cefc00343036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>e67e7ed4-cb54-4437-be61-f8a030a387ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
