<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manual allocation</name>
   <tag></tag>
   <elementGuidId>9daab4ff-1da6-428c-8cb1-c53fa7328fbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#manuallocationbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manuallocationbtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Manual Allocate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>450beeb3-6666-4811-ab9b-84bcbd5461c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manuallocationbtn</value>
      <webElementGuid>05e6d9ee-34c3-44e1-86b5-cf01a5cd1213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Manual Allocate</value>
      <webElementGuid>7588f713-c8ff-4773-88c4-9cd3f908eab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fb7e1034-1d77-4621-8a8e-ddbc35447fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btncls manuallocationbtncls</value>
      <webElementGuid>b8353754-922a-469b-b6b1-41f4567ec5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ManualAllocationMethod(this,'MA')</value>
      <webElementGuid>c324baa3-fcb5-487f-b776-3ebe9a4a440c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manuallocationbtn&quot;)</value>
      <webElementGuid>ce693e60-40f0-4da5-b5ff-b4b73f156fc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manuallocationbtn']</value>
      <webElementGuid>22a8421f-57e6-485d-ac1d-59d2a2d1014f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divmanuallocationbtn']/input</value>
      <webElementGuid>8d34982d-4fd8-4034-99e5-96827b455032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>264b21c7-b75c-477f-8bae-f62d72b6f7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'manuallocationbtn' and @type = 'submit']</value>
      <webElementGuid>82d5fe15-917d-4f3d-a375-fdbfb3ab3035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
