<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select user</name>
   <tag></tag>
   <elementGuidId>0529d819-96d3-4970-a0ea-ac5126495a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=&quot;ddlpopupusrLst&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ddlpopupusrLst</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ddlpopupusrLst</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2f9b31ca-883f-4880-929c-3c1eb3985ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-control w-100</value>
      <webElementGuid>72a9942e-3dda-4248-bacd-a1c6bf438edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddlpopupusrLst</value>
      <webElementGuid>201d28ad-0201-45f8-8365-c08d0ca911fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlpopupusrLst</value>
      <webElementGuid>1940a8c4-42a3-4f60-bcef-591f5b36ee9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectD02355Usr1 - Kailash  DumpalaN02684Usr2 - Nerella  Shiva Kumar</value>
      <webElementGuid>95236fe8-1451-4d94-ac5f-8a8753b19daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlpopupusrLst&quot;)</value>
      <webElementGuid>025c33ca-eabf-4ea0-8e31-6acad9c59279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlpopupusrLst']</value>
      <webElementGuid>de395bb2-3f28-49de-bd3c-f2d700104839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmallocation']/div/div/div/select</value>
      <webElementGuid>0c068428-489a-4fd7-8011-a30555502180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/following::select[1]</value>
      <webElementGuid>6a90e8f4-e798-4031-9603-3836491e9f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/following::select[1]</value>
      <webElementGuid>57e4b508-e058-4405-b12a-00e0ee595f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[1]</value>
      <webElementGuid>434a530c-9e2e-4b5f-8159-c430cab66c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/preceding::select[1]</value>
      <webElementGuid>4b6c0f38-b3e3-4dbe-ac21-8d31a51f790c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/select</value>
      <webElementGuid>26ae688c-8d21-4186-880b-18a0a2081625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ddlpopupusrLst' and @id = 'ddlpopupusrLst' and (text() = 'SelectD02355Usr1 - Kailash  DumpalaN02684Usr2 - Nerella  Shiva Kumar' or . = 'SelectD02355Usr1 - Kailash  DumpalaN02684Usr2 - Nerella  Shiva Kumar')]</value>
      <webElementGuid>43b1dd53-ed09-413c-bdb1-1344406fffd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
