<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClaimantGender</name>
   <tag></tag>
   <elementGuidId>51166bc8-3822-4f58-bee8-004fb8c11303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id,'selCDGender')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
