<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proposal_no</name>
   <tag></tag>
   <elementGuidId>ae00963f-d476-4f18-8e48-7281fd321934</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Claims Tracker - SHRILIFE/Proposal_no.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtbxfltrfldsval</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtbxfltrfldsval']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Claims Tracker - SHRILIFE/Proposal_no.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c5272f8-0b2c-4d6b-8a64-6653f4d88422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txtbxfltrfldsvalcls</value>
      <webElementGuid>ce908c44-8060-40f5-bab2-bd7727dfbdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95240c2c-18e1-4512-b724-310951436bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtbxfltrfldsval</value>
      <webElementGuid>b3f49a1e-d875-43b3-b95a-3885ab034d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>85447a55-9a61-44fb-bfc3-6a26e05b32f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>updateFilter(this)</value>
      <webElementGuid>b810a40a-1572-411d-919a-63d3d66e4056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>c9c97c1b-076f-4f2f-89d9-77cc883e8e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtbxfltrfldsval&quot;)</value>
      <webElementGuid>ab221f42-9f33-44d1-b00a-e37d59c683b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtbxfltrfldsval']</value>
      <webElementGuid>2da6f48b-6b44-405d-9a5b-49ddf1827d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OCclaimsdiv']/div/div/div[2]/div/div/input</value>
      <webElementGuid>6c32e405-d2bb-4322-8178-754680213911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>678cf81f-572e-4402-9671-83094602aab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtbxfltrfldsval' and @placeholder = 'Search']</value>
      <webElementGuid>e6101efc-3872-4d36-b141-fc0e25e2dbd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
