<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Remark</name>
   <tag></tag>
   <elementGuidId>1bd7183f-f47d-4d17-a35e-091c4b002bba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtremarks</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtremarks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtremarks</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3493f04a-42c0-4642-b5fa-358111a9dde0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control borderredcls</value>
      <webElementGuid>93cfebc3-8489-430b-b705-07e5469d6e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtremarks</value>
      <webElementGuid>19b0e2a4-bd4a-42c7-a538-d3af1c72c280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>StatusValidation()</value>
      <webElementGuid>a40f9216-cde2-4f1c-a5d3-bc8475368ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtremarks</value>
      <webElementGuid>1c775962-422e-44d1-8c67-9de56abc2f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ef8236f6-ff86-47c9-ad4a-cec74dec546f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>b977ca3f-3ec0-4f70-940f-1610b2a522fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>e741a9c2-337b-4f17-8829-e8bf50a26902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtremarks&quot;)</value>
      <webElementGuid>4c420d36-e56a-41fb-a9ef-6536ded4ec04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtremarks']</value>
      <webElementGuid>6a2b24fd-4f12-4ca8-8549-54e621ffd85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divremarks']/textarea</value>
      <webElementGuid>6ce7dc02-3998-48f1-8724-d5bbe797487c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6a5afeda-7147-4db6-9087-30e793cea4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtremarks' and @name = 'txtremarks']</value>
      <webElementGuid>93c402a6-b1bf-4e2f-940f-67ef97b4ed20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
