<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//*[@id=&quot;dm0m18i8tdT&quot;]</description>
   <name>accountReport</name>
   <tag></tag>
   <elementGuidId>bfc919d1-480f-4ed8-a138-c0d021cd0f7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dm0m13i5tdT&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
