<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_policy_no</name>
   <tag></tag>
   <elementGuidId>600f99bb-d085-4373-82b4-752e49712eb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtbxfltrfldsval</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtbxfltrfldsval1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7895331-df55-46e6-9806-a2fa1187c0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txtbxfltrfldsvalcls</value>
      <webElementGuid>d919c6e4-1930-431b-9ae6-82894e99a299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97161364-e140-4e4a-a4ef-225fa8fc3e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtbxfltrfldsval</value>
      <webElementGuid>25264863-83d7-466e-9035-19b8185ac670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>249374a5-b6d9-4a5b-b8aa-46a5648a21bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>updateFilter(this)</value>
      <webElementGuid>771315f1-da8f-4943-93cb-845dd0e5f040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b4138ba2-533c-4bdc-9cf6-80261188ebbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtbxfltrfldsval&quot;)</value>
      <webElementGuid>b8e5b8b0-f29a-4910-9f82-bedf8971e969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtbxfltrfldsval']</value>
      <webElementGuid>fe2f9374-a308-4647-aee7-d041095e4964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hideshowbtndiv']/div/input</value>
      <webElementGuid>3b9c5ef1-eafa-473a-a1ce-7b5c26307959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/input</value>
      <webElementGuid>b0f77f95-c99c-4299-961a-ccddbb050350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtbxfltrfldsval' and @placeholder = 'Search']</value>
      <webElementGuid>90766d01-7949-4d21-90eb-957cc1b3641e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
