<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox</name>
   <tag></tag>
   <elementGuidId>8d430b8b-d545-4617-9ce7-ebc88ed60997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@tabulator-field='PolicyNo' and text()='${policyNo}'] /ancestor::div[@role='row']/div[@class='tabulator-cell'][1]//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.katalonDeHighlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;NNST2406061491 MANONMANI 10/06/2024 InForce Fully Paid Up CRM View View View View View View View 20/11/2024 07/03/2026 3 Days&quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18a4521e-143c-4e0c-b7e5-bb748ebd6b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e3aefb53-56f4-4e03-ac79-22df9910a2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> katalonDeHighlight</value>
      <webElementGuid>61e27148-a03a-4886-9815-0c5083551934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-table&quot;)/div[@class=&quot;tabulator-tableholder&quot;]/div[@class=&quot;tabulator-table&quot;]/div[@class=&quot;tabulator-row tabulator-selectable tabulator-row-odd tabulator-tree-level-0 tabulator-selected&quot;]/div[@class=&quot;tabulator-cell&quot;]/input[@class=&quot;katalonDeHighlight&quot;]</value>
      <webElementGuid>49cf3760-0592-4a03-83a0-b772b9a80718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>6bfe3ea3-b4a9-4e3a-a38f-2b1b8c0916d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid-table']/div[2]/div/div/div/input</value>
      <webElementGuid>bbf8a8b7-31d2-4eb2-875a-dec0831b23c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>3ef77bdf-929e-455f-83a2-a740ffe53ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>369bce0c-ff02-45ea-91e7-accaabdef817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
