<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manual allocation</name>
   <tag></tag>
   <elementGuidId>97ac324d-da82-41f3-8271-e4f27d9fbb31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#manuallocationbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'manuallocationbtn' and @type = 'submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Manual Allocate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8998f0a8-76a5-4a9e-85d9-bca818314980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manuallocationbtn</value>
      <webElementGuid>e34c003c-9679-416f-be1b-dcdda134ac2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Manual Allocate</value>
      <webElementGuid>f99a4cf0-034f-42ff-a2ec-eeb15080e993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>08742554-c507-4009-aa33-a1b89e4e28df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btncls manuallocationbtncls</value>
      <webElementGuid>27a0da81-93a7-4d95-b0f0-0feeb694c5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ManualAllocationMethod(this,'MA')</value>
      <webElementGuid>2d89cce5-98a7-4871-8287-e7fd378bc2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manuallocationbtn&quot;)</value>
      <webElementGuid>afc3fec4-ec0d-4d6b-ad97-4a2f865bac1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manuallocationbtn']</value>
      <webElementGuid>64479a60-1e36-4ceb-86fe-2e4ad127965f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divmanuallocationbtn']/input</value>
      <webElementGuid>f9d0d032-5fe2-4646-b019-3f90176443ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>4f218cc9-1525-4ca8-87ac-34122c9f5aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'manuallocationbtn' and @type = 'submit']</value>
      <webElementGuid>a6629b00-a2b4-47a2-9761-e35b553f8558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
