<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select user</name>
   <tag></tag>
   <elementGuidId>bd8f2a9b-c2af-4c3d-a2d0-0ed57682b494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ddlpopupusrLst</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddlpopupusrLst']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ddlpopupusrLst</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aca7ce40-fee3-4d03-9233-301ed2d34bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-control w-100 borderredcls</value>
      <webElementGuid>41cce6f7-9a28-46b9-9c64-55d1f76d13fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddlpopupusrLst</value>
      <webElementGuid>efb06653-f3f1-4e21-883b-adda53017dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlpopupusrLst</value>
      <webElementGuid>e0e50f21-f5e6-4de5-be17-584af3dd84c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ddlpopupusrLst-error</value>
      <webElementGuid>b8101e50-e6d5-4c9a-8800-4b216fdb6b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f7ad8dcf-e2df-4d4b-a8c4-dfadfc7d853c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectA03357HDA - ARJUN KOPPULAA05139 - Naresh AmetiB03232 - Bivek SinghD02355 - Kailash DumpalaG01735 - Sharath GundetiK02389 - ChaitanyaK02645HDA - KOLLURU SHRAVAN KUMARK03738HDA - KAVELI VINEETH REDDYK03844 - K RavichanderM02931HDA - MAMIDI MAHESHWAR REDDYM04131 - Mulinti Pradeep ReddyM04411HDA - MOHAMMED GHOUSE KHANM05138 - M Praveen KumarM05919HDA - MALLAM MANISHAN02535 - Sairam NN02684 - N Shiva KumarOFFINT2423 - BhargaviOFFINT2431 - HeenaP02818 - Pyla Sai Madhavi KrishnaP04303 - Punugoti PrasadProrisk1 - Pro risk 1Prorisk2 - Pro risk2Prorisk3 - Pro risk3S07267HDA - SIDAM SRIDEVIS09520 - Sandeep DasS11255 - Sanjib DasS11255CA - Sanjib DasS11600HDA - SOMMULA RAMYAT01161 - Thanem NagatejaU00536 - U Suresh KumarV03487 - Jagadevi VasaraV03770 - Venkata Narsimha Naidu</value>
      <webElementGuid>6a6a3150-b55d-4c0b-8b0d-285e98b14e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlpopupusrLst&quot;)</value>
      <webElementGuid>d58d8569-5a01-4bc9-8d9d-bef78268d4e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlpopupusrLst']</value>
      <webElementGuid>39659bfa-7d13-44e7-bbaa-aa7400fe81a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmallocation']/div/div/div/select</value>
      <webElementGuid>7ce55aff-0cb7-42ff-acf6-47537cb6b822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/following::select[1]</value>
      <webElementGuid>d98aaa8b-0081-4f17-8afb-47ef936f9792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/following::select[1]</value>
      <webElementGuid>82f0382c-0c57-46a6-9d0a-2958e767998a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the user.'])[1]/preceding::select[1]</value>
      <webElementGuid>a1e168e9-b5c5-4d8f-b89a-d80a94c2ef6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[1]</value>
      <webElementGuid>4f874cce-5f0f-4d38-8b83-a019ad040ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/select</value>
      <webElementGuid>84770017-e2a8-44d0-a21c-bafc40d57e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ddlpopupusrLst' and @id = 'ddlpopupusrLst' and (text() = 'SelectA03357HDA - ARJUN KOPPULAA05139 - Naresh AmetiB03232 - Bivek SinghD02355 - Kailash DumpalaG01735 - Sharath GundetiK02389 - ChaitanyaK02645HDA - KOLLURU SHRAVAN KUMARK03738HDA - KAVELI VINEETH REDDYK03844 - K RavichanderM02931HDA - MAMIDI MAHESHWAR REDDYM04131 - Mulinti Pradeep ReddyM04411HDA - MOHAMMED GHOUSE KHANM05138 - M Praveen KumarM05919HDA - MALLAM MANISHAN02535 - Sairam NN02684 - N Shiva KumarOFFINT2423 - BhargaviOFFINT2431 - HeenaP02818 - Pyla Sai Madhavi KrishnaP04303 - Punugoti PrasadProrisk1 - Pro risk 1Prorisk2 - Pro risk2Prorisk3 - Pro risk3S07267HDA - SIDAM SRIDEVIS09520 - Sandeep DasS11255 - Sanjib DasS11255CA - Sanjib DasS11600HDA - SOMMULA RAMYAT01161 - Thanem NagatejaU00536 - U Suresh KumarV03487 - Jagadevi VasaraV03770 - Venkata Narsimha Naidu' or . = 'SelectA03357HDA - ARJUN KOPPULAA05139 - Naresh AmetiB03232 - Bivek SinghD02355 - Kailash DumpalaG01735 - Sharath GundetiK02389 - ChaitanyaK02645HDA - KOLLURU SHRAVAN KUMARK03738HDA - KAVELI VINEETH REDDYK03844 - K RavichanderM02931HDA - MAMIDI MAHESHWAR REDDYM04131 - Mulinti Pradeep ReddyM04411HDA - MOHAMMED GHOUSE KHANM05138 - M Praveen KumarM05919HDA - MALLAM MANISHAN02535 - Sairam NN02684 - N Shiva KumarOFFINT2423 - BhargaviOFFINT2431 - HeenaP02818 - Pyla Sai Madhavi KrishnaP04303 - Punugoti PrasadProrisk1 - Pro risk 1Prorisk2 - Pro risk2Prorisk3 - Pro risk3S07267HDA - SIDAM SRIDEVIS09520 - Sandeep DasS11255 - Sanjib DasS11255CA - Sanjib DasS11600HDA - SOMMULA RAMYAT01161 - Thanem NagatejaU00536 - U Suresh KumarV03487 - Jagadevi VasaraV03770 - Venkata Narsimha Naidu')]</value>
      <webElementGuid>c75cb869-ae4d-41db-950c-4cc17cea4eb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
